/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Apresentacao;

/**
 *
 * @author suporte
 */
public class CalculadoraJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName());

    /**
     * Creates new form CalculadoraJFrame
     */
    public CalculadoraJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jButton5 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTextDisplay = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ButtonAC = new javax.swing.JButton();
        ButtonTrocaSinal = new javax.swing.JButton();
        ButtonPorecentagem = new javax.swing.JButton();
        ButtonDivisao = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonPontoDecimal = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonSub = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonSoma = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonPotencia = new javax.swing.JButton();
        ButtonFechar = new javax.swing.JButton();
        ButtonIgualdade = new javax.swing.JButton();

        jButton5.setText("jButton5");

        jButton21.setText("jButton21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTextDisplay.setEditable(false);
        jTextDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jTextDisplay.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDisplay.setText("0,00");
        jTextDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDisplayActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        ButtonAC.setText("AC");
        ButtonAC.setToolTipText("");
        ButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonACActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAC);

        ButtonTrocaSinal.setText("+/-");
        jPanel1.add(ButtonTrocaSinal);

        ButtonPorecentagem.setText("%");
        jPanel1.add(ButtonPorecentagem);

        ButtonDivisao.setText("/");
        ButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivisaoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDivisao);

        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        jPanel1.add(Button7);

        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        jPanel1.add(Button8);

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        jPanel1.add(Button9);

        ButtonPontoDecimal.setText(".");
        ButtonPontoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPontoDecimalActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPontoDecimal);

        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        jPanel1.add(Button4);

        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        jPanel1.add(Button5);

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        jPanel1.add(Button6);

        ButtonSub.setText("-");
        ButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSub);

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1);

        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2);

        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel1.add(Button3);

        ButtonSoma.setText("+");
        ButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSomaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSoma);

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        jPanel1.add(Button0);

        ButtonPotencia.setText("x²");
        ButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPotenciaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPotencia);

        ButtonFechar.setText("Fechar");
        ButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFecharActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonFechar);

        ButtonIgualdade.setText("=");
        ButtonIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualdadeActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIgualdade);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTextDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDisplayActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void ButtonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonACActionPerformed
         TexDisplay.setText("");
    }//GEN-LAST:event_ButtonACActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "3");        }//GEN-LAST:event_Button3ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "7");      }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "8");      }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "9");      }//GEN-LAST:event_Button9ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "4");      }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "5");      }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "6");      }//GEN-LAST:event_Button6ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
   String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "1");    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "2");      }//GEN-LAST:event_Button2ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "0");      }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPotenciaActionPerformed
 String TextoAtual = TexDisplay.get.Text();
        txtVisor.setText(TextoAtual + "²");      }//GEN-LAST:event_ButtonPotenciaActionPerformed

    private void ButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFecharActionPerformed
        System.exit(0);    }//GEN-LAST:event_ButtonFecharActionPerformed

    private void ButtonIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualdadeActionPerformed
private void ButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {                                             
    String expressao =TexDisplay.getText();                                             

public class CalculadoraSimples extends JFrame {
    private JTextField txtDisplay;
    private double num1, num2, resultado;
    private String operacao;

    public CalculadoraSimples() {
        setSize(300, 150);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        txtDisplay = new JTextField();
        txtDisplay.setBounds(20, 20, 250, 30);
        add(txtDisplay);

        JButton btnMais = new JButton("+");
        btnMais.setBounds(20, 60, 50, 30);
        add(btnMais);

        JButton btnIgual = new JButton("=");
        btnIgual.setBounds(80, 60, 50, 30);
        add(btnIgual);

        // Quando clicar no botão +
        btnMais.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    num1 = Double.parseDouble(txtDisplay.getText());
                    operacao = "+";
                    txtDisplay.setText("");
                } catch (NumberFormatException ex) {
                    txtDisplay.setText("Erro");
                }
            }
        });

        // Quando clicar no botão =
        btnIgual.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    num2 = Double.parseDouble(txtDisplay.getText());
                    if (operacao.equals("+")) {
                        resultado = num1 + num2;
                    }
                    txtDisplay.setText(String.valueOf(resultado));
                } catch (Exception ex) {
                    txtDisplay.setText("Erro");
                }
            }
        });
    }

    public static void main(String[] args) {
        new CalculadoraSimples().setVisible(true);
    }
    }//GEN-LAST:event_ButtonIgualdadeActionPerformed

    private void ButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSomaActionPerformed
 String TextoAtual = txtVisor.get.Text();
        txtVisor.setText(TextoAtual + "+");      }//GEN-LAST:event_ButtonSomaActionPerformed

    private void ButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubActionPerformed
 String TextoAtual = txtVisor.get.Text();
        txtVisor.setText(TextoAtual + "-");      }//GEN-LAST:event_ButtonSubActionPerformed

    private void ButtonPontoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPontoDecimalActionPerformed
 String TextoAtual = txtVisor.get.Text();
        txtVisor.setText(TextoAtual + ".");      }//GEN-LAST:event_ButtonPontoDecimalActionPerformed

    private void ButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivisaoActionPerformed
 String TextoAtual = txtVisor.get.Text();
        txtVisor.setText(TextoAtual + "/");      }//GEN-LAST:event_ButtonDivisaoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAC;
    private javax.swing.JButton ButtonDivisao;
    private javax.swing.JButton ButtonFechar;
    private javax.swing.JButton ButtonIgualdade;
    private javax.swing.JButton ButtonPontoDecimal;
    private javax.swing.JButton ButtonPorecentagem;
    private javax.swing.JButton ButtonPotencia;
    private javax.swing.JButton ButtonSoma;
    private javax.swing.JButton ButtonSub;
    private javax.swing.JButton ButtonTrocaSinal;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton5;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDisplay;
    // End of variables declaration//GEN-END:variables
}
