/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculatrix.calculatrixlogin;

/**
 *
 * @author suporte
 */
public class CalculadoraJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName());

    private boolean novoNumero = true;
    private double ultimoValor = 0;
    private String ultimaOperacao = "";
    private String expressaoCompleta = "";

    /**
     * Creates new form CalculadoraJFrame
     */
    public CalculadoraJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(25, 40, 70));
        jPanel1.setBackground(new java.awt.Color(25, 40, 70));
        java.awt.Color azulBotao = new java.awt.Color(100, 150, 200);
        java.awt.Color textoEscuro = new java.awt.Color(25, 25, 35);
        javax.swing.JButton[] botoes = {Button0, Button1, Button2, Button3, Button4, Button5, Button6, Button7, Button8, Button9, ButtonAC, ButtonDivisao, ButtonFechar, ButtonIgualdade, ButtonPontoDecimal, ButtonPorecentagem, ButtonPotencia, ButtonSoma, ButtonSub, ButtonTrocaSinal};
        for (javax.swing.JButton btn : botoes) {
            btn.setBackground(azulBotao);
            btn.setForeground(textoEscuro);
            btn.setBorder(javax.swing.BorderFactory.createLineBorder(azulBotao.darker(), 1));
            btn.setFocusPainted(false);
        }
        jTextDisplay.setBackground(new java.awt.Color(25, 40, 70));
        jTextDisplay.setForeground(new java.awt.Color(100, 150, 200));
        jTextDisplay.setCaretColor(new java.awt.Color(100, 150, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jButton5 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTextDisplay = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ButtonAC = new javax.swing.JButton();
        ButtonTrocaSinal = new javax.swing.JButton();
        ButtonPorecentagem = new javax.swing.JButton();
        ButtonDivisao = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonPontoDecimal = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonSub = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonSoma = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonPotencia = new javax.swing.JButton();
        ButtonFechar = new javax.swing.JButton();
        ButtonIgualdade = new javax.swing.JButton();
        labelOperacao = new javax.swing.JLabel("");
        labelOperacao.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        labelOperacao.setForeground(new java.awt.Color(70, 130, 180));

        jButton5.setText("jButton5");

        jButton21.setText("jButton21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Abyssinica SIL", 1, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTextDisplay.setEditable(false);
        jTextDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jTextDisplay.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDisplay.setText("0,00");
        jTextDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDisplayActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        ButtonAC.setText("AC");
        ButtonAC.setToolTipText("");
        ButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonACActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAC);

        ButtonTrocaSinal.setText("x");
        ButtonTrocaSinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao("*");
            }
        });
        jPanel1.add(ButtonTrocaSinal);

        ButtonPorecentagem.setText("%");
        jPanel1.add(ButtonPorecentagem);

        ButtonDivisao.setText("/");
        ButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivisaoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDivisao);

        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        jPanel1.add(Button7);

        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        jPanel1.add(Button8);

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        jPanel1.add(Button9);

        ButtonPontoDecimal.setText(".");
        ButtonPontoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPontoDecimalActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPontoDecimal);

        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        jPanel1.add(Button4);

        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        jPanel1.add(Button5);

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        jPanel1.add(Button6);

        ButtonSub.setText("-");
        ButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSub);

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1);

        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2);

        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel1.add(Button3);

        ButtonSoma.setText("+");
        ButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSomaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSoma);

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        jPanel1.add(Button0);

        ButtonPotencia.setText("x²");
        ButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPotenciaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPotencia);

        ButtonFechar.setText("Voltar");
        ButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new TelaDeEscolha().setVisible(true);
                CalculadoraJFrame.this.dispose();
            }
        });
        jPanel1.add(ButtonFechar);

        ButtonIgualdade.setText("=");
        ButtonIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualdadeActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIgualdade);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelOperacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTextDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                    .addComponent(labelOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDisplayActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void ButtonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonACActionPerformed
        jTextDisplay.setText("");
        novoNumero = true;
        ultimoValor = 0;
        ultimaOperacao = "";
        expressaoCompleta = "";
        labelOperacao.setText("");
    }//GEN-LAST:event_ButtonACActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        inserirNumero("3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        inserirNumero("7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        inserirNumero("8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        inserirNumero("9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        inserirNumero("4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        inserirNumero("5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        inserirNumero("6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        inserirNumero("1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        inserirNumero("2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        inserirNumero("0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPotenciaActionPerformed
        try {
            double valor = Double.parseDouble(jTextDisplay.getText());
            valor = Math.pow(valor, 2);
            jTextDisplay.setText(formatarResultado(valor));
            novoNumero = true;
            labelOperacao.setText(formatarResultado(valor) + " x²");
        } catch (Exception e) {
            jTextDisplay.setText("Erro");
            labelOperacao.setText("");
        }
    }//GEN-LAST:event_ButtonPotenciaActionPerformed

    private void ButtonIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualdadeActionPerformed
        calcularResultado();
        expressaoCompleta = "";
    }//GEN-LAST:event_ButtonIgualdadeActionPerformed

    private void ButtonPontoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPontoDecimalActionPerformed
        if (novoNumero) {
            jTextDisplay.setText("0.");
            novoNumero = false;
        } else if (!jTextDisplay.getText().contains(".")) {
            jTextDisplay.setText(jTextDisplay.getText() + ".");
        }
    }//GEN-LAST:event_ButtonPontoDecimalActionPerformed

    private void ButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSomaActionPerformed
        operacao("+");
    }//GEN-LAST:event_ButtonSomaActionPerformed

    private void ButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubActionPerformed
        operacao("-");
    }//GEN-LAST:event_ButtonSubActionPerformed

    private void ButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivisaoActionPerformed
        operacao("/");
    }//GEN-LAST:event_ButtonDivisaoActionPerformed

    private void ButtonPorecentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPorecentagemActionPerformed
        try {
            double valor = Double.parseDouble(jTextDisplay.getText());
            valor = valor / 100.0;
            jTextDisplay.setText(formatarResultado(valor));
            novoNumero = true;
            labelOperacao.setText(formatarResultado(valor) + " %");
        } catch (Exception e) {
            jTextDisplay.setText("Erro");
            labelOperacao.setText("");
        }
    }//GEN-LAST:event_ButtonPorecentagemActionPerformed

    private void operacao(String op) {
        try {
            double valorAtual = Double.parseDouble(jTextDisplay.getText());
            if (!ultimaOperacao.isEmpty()) {
                if (!novoNumero) {
                    calcularResultado();
                }
                ultimaOperacao = op;
            } else {
                ultimoValor = valorAtual;
                ultimaOperacao = op;
                novoNumero = true;
            }
            // Sempre adiciona o operador à expressão, mesmo se novoNumero for true
            expressaoCompleta += op;
            labelOperacao.setText(expressaoCompleta);
        } catch (Exception e) {
            jTextDisplay.setText("Erro");
            labelOperacao.setText("");
        }
    }

    private void calcularResultado() {
        try {
            double valorAtual = Double.parseDouble(jTextDisplay.getText());
            switch (ultimaOperacao) {
                case "+":
                    ultimoValor += valorAtual;
                    break;
                case "-":
                    ultimoValor -= valorAtual;
                    break;
                case "/":
                    if (valorAtual == 0) {
                        jTextDisplay.setText("Erro");
                        ultimaOperacao = "";
                        novoNumero = true;
                        labelOperacao.setText("");
                        return;
                    }
                    ultimoValor /= valorAtual;
                    break;
                case "*":
                    ultimoValor *= valorAtual;
                    break;
                default:
                    ultimoValor = valorAtual;
            }
            jTextDisplay.setText(formatarResultado(ultimoValor));
            ultimaOperacao = "";
            novoNumero = true;
            labelOperacao.setText("");
        } catch (Exception e) {
            jTextDisplay.setText("Erro");
            labelOperacao.setText("");
        }
    }

    private void inserirNumero(String num) {
        if (novoNumero) {
            jTextDisplay.setText(num);
            novoNumero = false;
        } else {
            jTextDisplay.setText(jTextDisplay.getText() + num);
        }
        atualizarExpressao(num);
    }

    private void atualizarExpressao(String novo) {
        if (novoNumero && (novo.equals("+") || novo.equals("-") || novo.equals("*") || novo.equals("/"))) {
            // Não adiciona operador se for novo número
            return;
        }
        expressaoCompleta += novo;
        labelOperacao.setText(expressaoCompleta);
    }

    private String formatarResultado(double valor) {
        if (valor == (long) valor)
            return String.format("%d", (long) valor);
        else
            return String.format("%s", valor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAC;
    private javax.swing.JButton ButtonDivisao;
    private javax.swing.JButton ButtonFechar;
    private javax.swing.JButton ButtonIgualdade;
    private javax.swing.JButton ButtonPontoDecimal;
    private javax.swing.JButton ButtonPorecentagem;
    private javax.swing.JButton ButtonPotencia;
    private javax.swing.JButton ButtonSoma;
    private javax.swing.JButton ButtonSub;
    private javax.swing.JButton ButtonTrocaSinal;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton5;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDisplay;
    private javax.swing.JLabel labelOperacao;
    // End of variables declaration//GEN-END:variables
}
