/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculatrix.calculatrixlogin;

import com.calculatrix.calculatrixlogin.tictactoe;
import com.calculatrix.calculatrixlogin.CalculadoraJFrame;
import javax.swing.ImageIcon;

/**
 *
 * @author Maxwell
 */
public class TelaDeEscolha extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeEscolha
     */
    public TelaDeEscolha() {
        initComponents();
        setTitle("Calculatrix");
        setLocationRelativeTo(null);
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/calculatrix/calculatrixlogin/images/calculaTRIX (1).png"));
            setIconImage(icon.getImage());
        } catch (Exception e) {
            // Se não encontrar o ícone, não faz nada
        }
        setSize(600, 450);
        setResizable(false);
        setIconeCalculatrix();
        melhorarAparencia();
        adicionarImagemCalculatrix();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void melhorarAparencia() {
        jPanel1.setBackground(new java.awt.Color(25, 25, 35));
    }

    private void adicionarImagemCalculatrix() {
        try {
            java.awt.Image imagemOriginal = javax.imageio.ImageIO.read(
                getClass().getResourceAsStream("/com/calculatrix/calculatrixlogin/images/calculaTRIX (1).png")
            );
            java.awt.Image imagemRedimensionada = imagemOriginal.getScaledInstance(140, 140, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel labelImagem = new javax.swing.JLabel(new javax.swing.ImageIcon(imagemRedimensionada));
            labelImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jPanel1.setLayout(null);
            labelImagem.setBounds((600-140)/2, 30, 140, 140);

            java.awt.Image imgCalc = javax.imageio.ImageIO.read(
                getClass().getResourceAsStream("/com/calculatrix/calculatrixlogin/images/CalculadoraIcone (1).png")
            );
            java.awt.Image imgMem = javax.imageio.ImageIO.read(
                getClass().getResourceAsStream("/JOGODAVELHAICONE (1).png")
            );
            java.awt.Image imgCalcRed = imgCalc.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            java.awt.Image imgMemRed = imgMem.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel labelCalc = new javax.swing.JLabel(new javax.swing.ImageIcon(imgCalcRed));
            javax.swing.JLabel labelMem = new javax.swing.JLabel(new javax.swing.ImageIcon(imgMemRed));
            labelCalc.setBounds(160, 200, 100, 100);
            labelMem.setBounds(340, 200, 100, 100);
            labelCalc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            labelMem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            labelCalc.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    new CalculadoraJFrame().setVisible(true);
                    TelaDeEscolha.this.dispose();
                }
            });
            labelMem.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    new tictactoe(TelaDeEscolha.this);
                }
            });

            // Nome abaixo dos ícones
            javax.swing.JLabel nomeCalc = new javax.swing.JLabel("Calculadora");
            nomeCalc.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
            nomeCalc.setForeground(new java.awt.Color(70, 130, 180));
            nomeCalc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            nomeCalc.setBounds(160, 305, 100, 25);

            javax.swing.JLabel nomeMem = new javax.swing.JLabel("Jogo da Velha");
            nomeMem.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
            nomeMem.setForeground(new java.awt.Color(70, 130, 180));
            nomeMem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            nomeMem.setBounds(320, 305, 160, 25);

            jPanel1.add(labelImagem);
            jPanel1.add(labelCalc);
            jPanel1.add(labelMem);
            jPanel1.add(nomeCalc);
            jPanel1.add(nomeMem);
            jPanel1.repaint();
        } catch (Exception e) {
            System.err.println("Erro ao carregar a imagem: " + e.getMessage());
        }
    }

    private void setIconeCalculatrix() {
        try {
            java.awt.Image icone = javax.imageio.ImageIO.read(
                getClass().getResourceAsStream("/com/calculatrix/calculatrixlogin/images/calculaTRIX (1).png")
            );
            setIconImage(icone);
        } catch (Exception e) {
            System.err.println("Erro ao carregar o ícone: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeEscolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    class ImagePanel extends javax.swing.JPanel {
        private java.awt.Image backgroundImage;
        public ImagePanel() {
            try {
                backgroundImage = javax.imageio.ImageIO.read(getClass().getResource("/com/calculatrix/calculatrixlogin/images/fundo.png"));
            } catch (Exception e) {
                backgroundImage = null;
            }
        }
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            if (backgroundImage != null) {
                int panelWidth = getWidth();
                int panelHeight = getHeight();
                int imgWidth = backgroundImage.getWidth(this);
                int imgHeight = backgroundImage.getHeight(this);
                if (imgWidth > 0 && imgHeight > 0) {
                    double scale = Math.max((double)panelWidth / imgWidth, (double)panelHeight / imgHeight);
                    int newImgWidth = (int)(imgWidth * scale);
                    int newImgHeight = (int)(imgHeight * scale);
                    int x = (panelWidth - newImgWidth) / 2;
                    int y = (panelHeight - newImgHeight) / 2;
                    g.drawImage(backgroundImage, x, y, newImgWidth, newImgHeight, this);
                }
            }
        }
    }
}
